### ISSUE TITLE
Implement mitigation for incorrectly receipted new recurring contributions

### ISSUE THREAD

**Issue by bjendres** [systopia/de.systopia.donrec#105]
As exposed by #104 there is a serious issue in CiviCRM ``5.24.5`` (and others) that causes new contributions created by payment processors (via ``Contribution.repeattransaction``) to get copied the same "receipted" information. Those then cannot be receipted again.

Even though this needs to be fixed in CiviCRM, we want to put some mitigation in this extension:

1. Make sure (`Contribution.create` post hook) that there are no receipted information on a newly created contribution, i.e. delete values for the donrec custom fields
2. Create an algorithm that identifies and cleans up the potential mess created in the past.

**Comment by jensschuppe** [comment]
Will be released with version 2.0.

**Comment by bjendres** [comment]
Released with ``2.0``
