### ISSUE TITLE
5.31 compatibility: Tab "Donation receipts" on contact summary does not appear

### ISSUE THREAD

**Issue by Detsieber** [systopia/de.systopia.donrec#115]
The tab is not shown on the contact summary, after upgrade to CiviCRM 5.31.0

The functionality is still available via url:
Drupal8: ../civicrm/donrec/tab?cid=3134&force=1&reset=1&snippet=1
Wordpress: .../wp-admin/admin.php?page=CiviCRM&q=civicrm%2Fdonrec%2Ftab&reset=1&snippet=1&force=1&cid=11

But, the tab is lost.

It seems, that the technique used to inject the tab into the contact summary broke with the UI changes in CiviCRM 5.31

Hint: The siimilar issue happens for the civisepa extension, that probably uses the same mechanism.

**Comment by bjendres** [comment]
@Detsieber: could you verify that the fix above works? It's contained in [this version](https://github.com/systopia/de.systopia.donrec/archive/8ca8335ed2a9d59b3812f9d9794872777ed1a003.zip).

If it works we can create a ``2.0`` beta release

**Comment by jensschuppe** [comment]
@bjendres Please keep in mind that this needs to be cherry-picked to the `master` branch as well (since you branched `issue/115` off `release/2.x`).

**Comment by Detsieber** [comment]
Hi Björn,

I can verify: test works well for Wordpress!

However, for Drupal, I don't have a test system at hand...


Best
Detlev



Am 20.11.20 um 10:56 schrieb Björn Endres:

**Comment by bjendres** [comment]
Released with ``2.0``

**Comment by bjendres** [comment]
Released with ``2.0``

**Comment by tobiberlin** [comment]
@bjendres I updated to latest CiviCRM and lost the tab so I updated to the 2.0 version of this extension. But still the tab is missing. I run the extension upgrading and re-built the cachings but nothing changes

**Comment by tobiberlin** [comment]
When I enter the tab path directly as mentioned above (/civicrm/donrec/tab?reset=1&cid=XXX) I get an "Access denied" - this is new with the update to 2.0. Do I need configurate something new?

**Comment by tobiberlin** [comment]
Ok... I got it... I needed to set the permissions in the Drupal role / permission configuration.
