### ISSUE TITLE
Unable to set default profile when there is no current default profile

### ISSUE THREAD

**Issue by jojowork** [systopia/de.systopia.donrec#116]
I used a blank civicrm-installation and the new stable donrec 2.0 version
https://github.com/systopia/de.systopia.donrec/releases/download/2.0/de.systopia.donrec-2.0.zip
i made the database update and then clicked  http://localhost/test/civicrm/admin/setting/donrec/profile?op=default&id=1
to make the current profile to a default profile.
but then i got an error-message: Konnte kein Standard-Profil finden.
![donrec-bug](https://user-images.githubusercontent.com/40828981/100857322-dc3d4200-348c-11eb-8ab6-7c51aee733d2.png)

**Comment by jensschuppe** [comment]
Will be released with 2.1, also released with 2.0.1.
