### ISSUE TITLE
Broken button layout with CiviCRM >= 5.31

### ISSUE THREAD

**Issue by thomst** [systopia/de.systopia.donrec#121]
Since CiviCRM 5.31 the layout of all submit buttons of the extension specific formulars are broken.

This is related to the altered way CiviCRM renders its submit buttons since 5.31: https://civicrm.org/blog/eileen/prepare-civicrm-531-now-changes-could-affect-customisations

**Comment by sleidig** [comment]
I see the same problem - white text on white buttons since the last upgrade.

@bjendres, we don't have funding but I could contribute a PR if you are interested. Do you already have an approach in mind?

**Comment by bjendres** [comment]
> @bjendres, we don't have funding but I could contribute a PR if you are interested. 

Sure, PRs always welcome.

> Do you already have an approach in mind?

No, but the only condition is, that it needs to work on reasonable recent CiviCRM versions and with and without shoreditch.

**Comment by bbaermann** [comment]
This seems to be fixed in newer versions. I tried it with civicrm 5.50.1 and donrec 2.1-dev.
