### ISSUE TITLE
IDS: Can't create a profile with html in the Box "template".

### ISSUE THREAD

**Issue by ulimoebius** [systopia/de.systopia.donrec#123]
Auf Deutsch:
Nach Update auf Version 2.0, CiviCRM 5.19.1., Drupal 7
Wenn ich ein Profil anlege oder ein bestehend bearbeite, erscheint, nachdem ich "Speichern" gedrückt habe, folgender Fehler:
"Sorry, due to an error, we are unable to fulfill your request at the moment. You may want to contact your administrator or service provider with more details about what action you were performing when this occurred.
Validations Fehler im HTML Input. Ihre Aktion ist verdächtig und wird deshalb abgebrochen
Zur Anfangsseite zurück."
Nur wenn das Feld "Vorlage" leer bleibt, kommt keine Fehlermeldung und das Profil wird gespeichert.

English:
Can't creat a profil with html in the Box "Vorlage".

PS: die Vorlagenverwaltung über "Nachrichtenvorlagen" fand ich besser

**Comment by ulimoebius** [comment]
Wir haben einen "Workaround" gefunden:
wir haben in civicrm.settings.php die Variable "civicrm_ids_enable" auf 1.
unter "Drupal Access Control" gibt es die Berechtigung "CiviCRM: skip IDS check". Hier habe wir bei der Rolle, welche die Profile bearbeitet, ein Häcken gesetzt.

**Comment by bjendres** [comment]
Danke @ulimoebius. Das liegt vermutlich am Inhalt der Vorlagen - vermutlich können wir das IDS auch an dieser Stelle auch ausschalten.

**Comment by ulimoebius** [comment]
Das kann sein. Es betrifft aber auch eure Standartvorlage.

**Comment by jensschuppe** [comment]
I'll close this since there's a workaround and no similar complaints have been filed.
