### ISSUE TITLE
"rebook" function appears twice after CiviCRM update

### ISSUE THREAD

**Issue by mariav0** [systopia/de.systopia.donrec#130]
After I've updated on CiviCRM version 5.39.0 "rebook" appears twice.

![image](https://user-images.githubusercontent.com/70949178/125822521-e1c9d27c-48e9-4f7d-8be7-530eaca37fd1.png)

(I've disabled the extension to assure it is a bug from this extension.)

**Comment by muniodiego** [comment]
I have the same bug

**Comment by jensschuppe** [comment]
Can't seem to reproduce this (link always shows only once in the *more* menu) and the PR had been closed anyway. Feel free to reopen with steps to reproduce.
