### ISSUE TITLE
"rebook" function does not calculate correctly

### ISSUE THREAD

**Issue by mariav0** [systopia/de.systopia.donrec#131]
When I add a contribution (150 € including VAT) for contact A...

![image](https://user-images.githubusercontent.com/70949178/125823624-e947dc30-3435-4ea8-993c-16b8dfc40cc3.png)

and rebook this contribution to contact B, the VAT is added on top again:

![image](https://user-images.githubusercontent.com/70949178/125824100-59dd3035-1ae2-4942-955d-d316a36aa858.png)

(Tested on CiviCRM version 5.37.0 and 5.39.0)

--> more information here: https://lab.civicrm.org/dev/financial/-/issues/182#note_65652

**Comment by mariav0** [comment]
There is an extension (https://github.com/lcdservices/biz.lcdservices.movecontrib) which does the job already. Unfortunately it only works when donrec is deactivated. @bjendres  Would you mind cutting out this functionality from the donrec extension and enter a new release? Thank you in advance :)

**Comment by jaapjansma** [comment]
@bjendres I will make sure that this extension the movecontrib extension are compatible with each other without losing any functionality.

**Comment by bjendres** [comment]
Thanks Jaap. Will be released with ``2.0.2`` or with ``2.1``.
