### ISSUE TITLE
Button "view" doesn't work and when creating a copy, also no download-button appears

### ISSUE THREAD

**Issue by romymy** [systopia/de.systopia.donrec#132]
Wordpress 5.7.2, CiviCRM 5.38.0, donrec 2.0 >> When I create a copy of an original donation receipt, I only get the button "view" (not "download"). This happens regardless of whether I have activated the option "Store original PDF files" in the donrec profile or not. 

If a donation receipt is created, it usually is displayed in the log, eg.
_[info] de.systopia.donrec: resulting PDF file URL is '/wp-admin/admin.php?page=CiviCRM&q=civicrm%2Fdonrec%2Fshowfile&path=rhbCRw&name=donationreceipt-12-20210727142839-Fjplkr.pdf'_ 
and I can find the file in the CiviCRM file system (only when "Store original PDF files" is active). 

But when creating a copy, there is no log entry and no file. The button links to _.../wp-admin/admin.php?page=CiviCRM&q=civicrm%2Fdonrec%2Fshowfile&path=2e4aSG&name=DonationReceipt-12-13.pdf_ and Firefox/Chrome tries to interprete and shows sth. like this: 
![Screenshot 2021-07-29 at 10-46-28](https://user-images.githubusercontent.com/88038958/127461646-cab7d3dd-1edb-4144-a128-203482c28887.png)

In the donrec profile is an option to define a watermark for copies, so I expected that there would be not only a way to create a copy but then download or view it.  

Edit: It seems to be a wordpress only problem. On a Drupal /CiviCRM 5.37.0 the view button works fine.

**Comment by romymy** [comment]
I got a hint, that this issue is fixed in version 2.0.1. Using the view-button of a copy now results in a download and this file includes the copy-watermark. Thanks

**Comment by Detsieber** [comment]
This is a duplicate of #61 
Unfortunately, this fix is not contained in 2.0.1, but is tagged for 2.1

**Comment by Detsieber** [comment]
Also a duplicate of #122 (where the fix is provided)
