### ISSUE TITLE
[meta] Remove/replace deprecated CiviCRM Core code

### ISSUE THREAD

**Issue by jensschuppe** [systopia/de.systopia.donrec#138]
- [x] `CRM_Core_OptionGroup::getValue()` - #125
- [ ] `CRM_Core_Form::addDateRange()` - #181

**Comment by jojowork** [comment]
this is important now, because in the newest Version of CiviCRM the Function was removed and it is causing errors in CiviCRM

**Comment by Luensche** [comment]
It would be good if the addDateRange problem would be solved soon.
I'm getting the following exception on creating "Zuwendungsbescheinigungen":
`Deprecated: Deprecated function CRM_Core_Form::addDateRange, use Use CRM_Core_Form::addDatePickerRange insted. in /var/www/html/wp-content/plugins/civicrm/civicrm/CRM/Core/Error.php on line 1096 Fatal error: Uncaught TypeError: count(): Argument #1 ($value) must be of type Countable|array, null given in /var/www/html/wp-content/uploads/civicrm/ext/de.systopia.donrec-2.2.0/CRM/Donrec/Form/Task/ContributeTask.php:114 Stack trace: #0 /var/www/html/wp-content/plugins/civicrm/civicrm/CRM/Core/Form.php(624): CRM_Donrec_Form_Task_ContributeTask->postProcess() #1 /var/www/html/wp-content/plugins/civicrm/civicrm/CRM/Core/StateMachine.php(144): CRM_Core_Form->mainProcess() #2 /var/www/html/wp-content/plugins/civicrm/civicrm/CRM/Core/QuickForm/Action/Next.php(43): CRM_Core_StateMachine->perform(Object(CRM_Donrec_Form_Task_ContributeTask), 'next', 'Next') #3 /var/www/html/wp-content/plugins/civicrm/civicrm/packages/HTML/QuickForm/Controller.php(203): CRM_Core_QuickForm_Action_Next->perform(Object(CRM_Donrec_Form_Task_ContributeTask), 'next') #4 /var/www/html/wp-content/plugins/civicrm/civicrm/packages/HTML/QuickForm/Page.php(103): HTML_QuickForm_Controller->handle(Object(CRM_Donrec_Form_Task_ContributeTask), 'next') #5 /var/www/html/wp-content/plugins/civicrm/civicrm/CRM/Core/Controller.php(355): HTML_QuickForm_Page->handle('next') #6 /var/www/html/wp-content/plugins/civicrm/civicrm/CRM/Core/Invoke.php(319): CRM_Core_Controller->run(Array, NULL) #7 /var/www/html/wp-content/plugins/civicrm/civicrm/CRM/Core/Invoke.php(69): CRM_Core_Invoke::runItem(Array) #8 /var/www/html/wp-content/plugins/civicrm/civicrm/CRM/Core/Invoke.php(36): CRM_Core_Invoke::_invoke(Array) #9 /var/www/html/wp-content/plugins/civicrm/civicrm.php(1199): CRM_Core_Invoke::invoke(Array) #10 /var/www/html/wp-includes/class-wp-hook.php(310): CiviCRM_For_WordPress->invoke('') #11 /var/www/html/wp-includes/class-wp-hook.php(334): WP_Hook->apply_filters('', Array) #12 /var/www/html/wp-includes/plugin.php(517): WP_Hook->do_action(Array) #13 /var/www/html/wp-admin/admin.php(259): do_action('toplevel_page_C...') #14 {main} thrown in /var/www/html/wp-content/uploads/civicrm/ext/de.systopia.donrec-2.2.0/CRM/Donrec/Form/Task/ContributeTask.php on line 114 `

**Comment by jensschuppe** [comment]
This should be fixed by #181, which seeks review. Intense testing and feedback much appreciated over there!
