### ISSUE TITLE
After upgrade to PHP 8.1: Array and string offset access syntax with curly braces is no longer supported

### ISSUE THREAD

**Issue by tobiberlin** [systopia/de.systopia.donrec#148]
The full error:

`Fatal error: Array and string offset access syntax with curly braces is no longer supported in \sites\default\files\civicrm\ext\de.systopia.donrec\donrec.civix.php on line 248`

I upgrade from the very old PHP 7.3 and I think the curly braces are deprecated from PHP 7.4 on

**Comment by jensschuppe** [comment]
Please try with version `2.1-beta1`, this has already been fixed in #139.
