### ISSUE TITLE
Exporting large number of transactions fails

### ISSUE THREAD

**Issue by sleidig** [systopia/de.systopia.donrec#150]
When trying to export transactions I run into an error if there is a large number of entries:

> Request-URI Too Long
> The requested URL's length exceeds the capacity limit for this server.

To reproduce:
1. Menu: Show Payments
2. Switch to "Completed", mark multiple statements, click "Show Transactions"
3. Select all entries and click "Export" at bottom of page

The selected ids are added to the URL only, which doesn't work for thousands of records anymore.

I am happy to hack together a workaround (or contribute to another implementation). Is there another common way you are using to pass around data for these kind of use cases?

**Comment by bjendres** [comment]
Hm, are you sure that this is related to this extension? It sounds like you're exporting financial transactions, which is part of the CiviCRM core. But if this is really a donrec issue, could you please be more detailed about how to reproduce it?

**Comment by sleidig** [comment]
Sorry, you are absolutely right - this was supposed to go into CiviBanking ...
