### ISSUE TITLE
PHP 8.0 Compatibility

### ISSUE THREAD

**Issue by abugey** [systopia/de.systopia.donrec#151]
* [x] Analyse code regarding PHP 8 compatibility
* [x] Fix deprecations found (to be specified)

**Comment by jensschuppe** [comment]
@abugey I added a description, feel free to edit it if there's something to add.

**Comment by abugey** [comment]
* [x] Analyse code regarding PHP 8 compatibility
- php linter: no errors
- PHP Storm inspect code: no PHP 8.0 specific errors
* [x] Fix deprecations found (to be specified)
- no fixes needed

**Comment by jensschuppe** [comment]
I merged the Civix-related stuff into `master`.
