### ISSUE TITLE
Errors from static code analysis: Undefined variables

### ISSUE THREAD

**Issue by abugey** [systopia/de.systopia.donrec#152]
Errors from static code analysis. Found by PhpStorms "Inspect Code" Feature.. These are marked errors (not only warnings!) in both PHP7.4 and PHP8.0

-  DonrecCustomisationHooks.php: `Undefined variable $chunk_item`
-  EmailPDF.php: `Undefined variable $snapshot_line_id`

**Comment by jensschuppe** [comment]
There are already `TODO`s in the code about those. Also, at least the first one doesn't seem to be called anywhere.

**Comment by jensschuppe** [comment]
I fixed those in fa72db18c05901314e0aeb4c7ee4af84da606929 and e2328e83ce2856d7ed60ff83a8db2c9af173cff3. Untested, but the first one is in presumably unused code and the second one follows a pattern found in other exporters and is for logging only.
