### ISSUE TITLE
PHP 8.0 compatibility

### ISSUE THREAD

**Issue by Detsieber** [systopia/de.systopia.donrec#158]
"Edit profile" (https://url... .de/wp-admin/admin.php?page=CiviCRM&q=civicrm%2Fadmin%2Fsetting%2Fdonrec%2Fprofile&op=edit&id=1) creates a wsod ...

However, the good news: As I tested, this is already fixed with the current master as of today (2023-02-05).

Could you please publish a tag or a release with that code?

**Comment by Detsieber** [comment]
This issue is simply for asking to get a release (or at least a tag) with the changes from #151

**Comment by bjendres** [comment]
> This issue is simply for asking to get a release (or at least a tag) with the changes from #151

I understand. The release will probably be tagged with ``2.1.0``, but my colleagues will still have to look into the things that are currently WIP or missing before the release.

**Comment by abugey** [comment]
Hey Detlef, 
the new release has been published today: [2.1.0](https://github.com/systopia/de.systopia.donrec/releases/tag/2.1.0)
I'm closing here now.
Best, Anna

**Comment by Detsieber** [comment]
Herzlichen Dank!
