### ISSUE TITLE
How to edit the template in Wordpress? (support request)

### ISSUE THREAD

**Issue by being-peace** [systopia/de.systopia.donrec#162]
I have done that already, but I don´t remember, how to do it.
I don´t see it listed under "Menü -> Administration -> Kommunikation -> Nachrichtenvorlagen -> System Workflow Nachricht -> Zuwendungsbescheinigungen - Standardvorlage" as described in https://wiki.civicrm.org/confluence/display/CRM/ZWB-Extension

**Comment by AHowiller** [comment]
There's a separate cofiguration screen for that. Just enter _Donation Receipts Profiles_ in the config quick search (hover CiviCRM logo top left in the main menue) or navigate Administer → Administration Console and scroll down to the CiviContribute section.

**Comment by jensschuppe** [comment]
Seems the question has been answered.

**Comment by being-peace** [comment]
Sorry, @AHowiller , somehow I did not see your comment. Thanks for commenting.

Yet, I can´t really edit the Template for the Donation Receipt  (what is written there).  Or where do I have to look at? 
![grafik](https://github.com/systopia/de.systopia.donrec/assets/58709258/997d5502-b022-4689-88a9-80b26a9f5583)

**Comment by AHowiller** [comment]
All you have to do is search for the English term: 
![screenshot_donrec_menue](https://github.com/systopia/de.systopia.donrec/assets/59540713/2577c416-2b2d-4bbe-b3ac-c5f18e5826a7)

**Comment by being-peace** [comment]
Because of my language setting it does not seem to be there, neither in German nor in English. But on 
https://www.XXX.de/wp-admin/admin.php?page=CiviCRM&q=civicrm%2Fadmin&reset=1
It is available in a German/English mixture. Possibly my problem is that some German translation have been missing.
![grafik](https://github.com/systopia/de.systopia.donrec/assets/58709258/ae9af64f-ede7-4136-9607-14924274bdb0)
