### ISSUE TITLE
"Rebook" isn't working properly

### ISSUE THREAD

**Issue by Detsieber** [systopia/de.systopia.donrec#167]
As of donrec 2.2.0, the rebook function isn't working properly anymore:

Error: "Expected one OptionValue but found 0"

> 
>  [error] 
> $Fatal Error Details = array:3 [
>   "message" => "Expected one OptionValue but found 0"
>   "code" => null
>   "exception" => CRM_Core_Exception {#4144
>     -errorData: array:4 [
>       "count" => 0
>       "is_error" => 1
>       "error_message" => "Expected one OptionValue but found 0"
>       "error_code" => "undefined"
>     ]
>     #cause: null
>     -_trace: null
>     #message: "Expected one OptionValue but found 0"
>     #code: 0
>     #file: "/var/www/civi.digitalcourage.de/drupal/vendor/civicrm/civicrm-core/api/api.php"
>     #line: 135
>     trace: {
>       /var/www/civi.digitalcourage.de/drupal/vendor/civicrm/civicrm-core/api/api.php:135 { …}
>       /var/www/civi.digitalcourage.de/drupal/web/sites/default/files/civicrm/ext/de.systopia.donrec/CRM/Donrec/CustomData.php:836 {
>         CRM_Donrec_CustomData::getOptionValue($group_name, $label, $label_field = 'label', $label_type = 'String', $value_field = 'value')
>         ›   $label_field => $label,
>         ›   'return' => $value_field
>         › ]);
>       }
>       /var/www/civi.digitalcourage.de/drupal/web/sites/default/files/civicrm/ext/de.systopia.donrec/CRM/Donrec/Form/Task/Rebook.php:170 { …}
>       /var/www/civi.digitalcourage.de/drupal/web/sites/default/files/civicrm/ext/de.systopia.donrec/CRM/Donrec/Form/Task/Rebook.php:62 { …}
>       /var/www/civi.digitalcourage.de/drupal/vendor/civicrm/civicrm-core/CRM/Core/Form.php:573 { …}
>       /var/www/civi.digitalcourage.de/drupal/vendor/civicrm/civicrm-core/CRM/Core/StateMachine.php:144 { …}
>       /var/www/civi.digitalcourage.de/drupal/vendor/civicrm/civicrm-core/CRM/Core/QuickForm/Action/Next.php:43 { …}
>       /var/www/civi.digitalcourage.de/drupal/vendor/civicrm/civicrm-packages/HTML/QuickForm/Controller.php:203 { …}
>       /var/www/civi.digitalcourage.de/drupal/vendor/civicrm/civicrm-packages/HTML/QuickForm/Page.php:103 { …}
>       /var/www/civi.digitalcourage.de/drupal/vendor/civicrm/civicrm-core/CRM/Core/Controller.php:355 { …}
>       /var/www/civi.digitalcourage.de/drupal/vendor/civicrm/civicrm-core/CRM/Utils/Wrapper.php:98 { …}
>       /var/www/civi.digitalcourage.de/drupal/vendor/civicrm/civicrm-core/CRM/Core/Invoke.php:292 { …}
>       /var/www/civi.digitalcourage.de/drupal/vendor/civicrm/civicrm-core/CRM/Core/Invoke.php:69 { …}
>       /var/www/civi.digitalcourage.de/drupal/vendor/civicrm/civicrm-core/CRM/Core/Invoke.php:36 { …}
>       /var/www/civi.digitalcourage.de/drupal/web/modules/contrib/civicrm/src/Civicrm.php:88 { …}
>       /var/www/civi.digitalcourage.de/drupal/web/modules/contrib/civicrm/src/Controller/CivicrmController.php:83 { …}
>       Drupal\civicrm\Controller\CivicrmController->main() {}
>       /var/www/civi.digitalcourage.de/drupal/web/core/lib/Drupal/Core/EventSubscriber/EarlyRenderingControllerWrapperSubscriber.php:123 { …}
>       /var/www/civi.digitalcourage.de/drupal/web/core/lib/Drupal/Core/Render/Renderer.php:580 { …}
>       /var/www/civi.digitalcourage.de/drupal/web/core/lib/Drupal/Core/EventSubscriber/EarlyRenderingControllerWrapperSubscriber.php:124 { …}
>       /var/www/civi.digitalcourage.de/drupal/web/core/lib/Drupal/Core/EventSubscriber/EarlyRenderingControllerWrapperSubscriber.php:97 { …}
>       /var/www/civi.digitalcourage.de/drupal/vendor/symfony/http-kernel/HttpKernel.php:169 { …}
>       /var/www/civi.digitalcourage.de/drupal/vendor/symfony/http-kernel/HttpKernel.php:81 { …}
>       /var/www/civi.digitalcourage.de/drupal/web/core/lib/Drupal/Core/StackMiddleware/Session.php:58 { …}
>       /var/www/civi.digitalcourage.de/drupal/web/core/lib/Drupal/Core/StackMiddleware/KernelPreHandle.php:48 { …}
>       /var/www/civi.digitalcourage.de/drupal/web/core/modules/page_cache/src/StackMiddleware/PageCache.php:106 { …}
>       /var/www/civi.digitalcourage.de/drupal/web/core/modules/page_cache/src/StackMiddleware/PageCache.php:85 { …}
>       /var/www/civi.digitalcourage.de/drupal/web/core/lib/Drupal/Core/StackMiddleware/ReverseProxyMiddleware.php:48 { …}
>       /var/www/civi.digitalcourage.de/drupal/web/core/lib/Drupal/Core/StackMiddleware/NegotiationMiddleware.php:51 { …}
>       /var/www/civi.digitalcourage.de/drupal/vendor/stack/builder/src/Stack/StackedHttpKernel.php:23 { …}
>       /var/www/civi.digitalcourage.de/drupal/web/core/lib/Drupal/Core/DrupalKernel.php:718 { …}
>       /var/www/civi.digitalcourage.de/drupal/web/index.php:19 { …}
>     }
>   }
> ]

I could reproduce this error with two different CiviCRM installs (with 5.58.1 and 5.61.1). 

This was still working at least with 2.0.1, and was broken with 2.2.Beta1.

**Comment by Detsieber** [comment]
The problem seems to be related with two things:

1. First it looks up the option_value for group_id = "Payment Instrument" and name = "OOFF" --> this fails, when CiviSEPA isn't installed. After installing CiviSEPA, it starts working - however only the first part is done (cancelling the original contribution).

2. Then, it looks up the option_value for group_id = "Payment_Instrument" and name = "4" ... which fails definitely.
In this case, "4" is the option value of the payment_instrument with the label of the contribution I tried to rebook. It seems like some mix up of option_name and option_value ...

**Comment by pminf** [comment]
For me it is crashing in `\CRM_Donrec_CustomData::getOptionValue` with the following params:
![rebook-api-call-failure](https://github.com/systopia/de.systopia.donrec/assets/611165/cbba1ac0-599b-4ad1-bfe5-0a318a6574b1)

This is a critical problem because **contributions are incorrectly canceled when you try to rebook**.

**Comment by bjendres** [comment]
Is it possible that this was observed on CiviCRM 5.60+? Then it's probably rather related to #138.

**Comment by bjendres** [comment]
> @pminf Is it possible that this was observed on CiviCRM 5.60+? Then it's probably rather related to #138.

Correction: it probably *is* related, but the mitigation seems broken.

**Comment by Detsieber** [comment]
As I wrote above:

> I could reproduce this error with two different CiviCRM installs (with 5.58.1 and 5.61.1).
> This was still working at least with 2.0.1, and was broken with 2.2.Beta1.

So, in fact it could be that the problem is related to the "fix" within donrec 2.2 !

**Comment by pminf** [comment]
We are currently using CiviCRM 5.61.4 with Donation Receipts 2.2.0, which we had to update because of deprecated functions (see https://github.com/systopia/de.systopia.donrec/issues/125). So yes, I assume that it worked with CiviCRM 5.59.4 and Donation Receipts 2.1.0.

**Comment by Detsieber** [comment]
The problem seems to be related with two things:

1. First it looks up the option_value for group_id = "Payment Instrument" and name = "OOFF" --> this fails, when CiviSEPA isn't installed. After installing CiviSEPA, it starts working - however only the first part is done (cancelling the original contribution).

2. Then, it looks up the option_value for group_id = "Payment_Instrument" and name = "4" ... which fails definitely.
In this case, "4" is the option value of the payment_instrument with the label of the contribution I tried to rebook. It seems like some mix up of option_name and option_value ...

**Comment by bjendres** [comment]
@Detsieber Could you confirm that @rubofvil's fix (#177) works?

**Comment by pminf** [comment]
At least for me it no longer crashes with the patch from #177 and the contribution seems to be reposted as expected.

**Comment by Detsieber** [comment]
Sorry for my late reply: I also tested and confirm that #177 is working. Issue is solved.
