### ISSUE TITLE
 Donrec 2.2.0 incompatible with php7.3

### ISSUE THREAD

**Issue by glatteis** [systopia/de.systopia.donrec#168]
The line
```
$context['contact_id'] ??= NULL;
```
throws a syntax error.

**Comment by jensschuppe** [comment]
This is in the extension code since version `2.1.0` actually. We decided to not support PHP <7.4 anymore, sorry. PHP 7.3 went EOL in November 2021. Unfortunately, there's no way to require a specific minimum PHP version via extension metadata. I'll add a note to the release notes though.

**Comment by glatteis** [comment]
Thanks!
