### ISSUE TITLE
Copy donation receipts inconsistent?

### ISSUE THREAD

**Issue by MarcMichalsky** [systopia/de.systopia.donrec#169]
Hi,

I think I have encountered an inconsistency in copying donation receipts.

When copying, the field `issued_on` is overwritten with the current date. This results in the generated copy also showing the current date and not the original issue date. (I am already using the `$issued_on` field in the template instead of `$today`)

Maybe this is intentional, but in this case it is a problem that not the current default profile but the original profile is used.

In our case, this leads to the fact that when we issue a copy of an older donation receipt, the current date is used and below it is the signature of our former board member, who does not work for us anymore.

So we have to make a decision at this point: Is a copy a true copy of the original donation receipt with the original date, or is it a new receipt with the current date and current profile (resp. template)?

**Comment by bjendres** [comment]
Thanks for reporting, @MarcMichalsky 

> Is a copy a true copy of the original donation receipt with the original date, or is it a new receipt with the current date and current profile (resp. template)?

I'll pass this on to the people who work with this most.

**Comment by MarcMichalsky** [comment]
Okay, it would be easy to fix. [This](https://github.com/systopia/de.systopia.donrec/compare/master...MarcMichalsky:de.systopia.donrec:issue/169) worked for me.

**Comment by MarcMichalsky** [comment]
We should also [adjust the default template](https://github.com/systopia/de.systopia.donrec/commit/97e6716ded97af974108f5e3ddbb285f1c6250b1) accordingly, otherwise the changes will not be applied.

Of course, many organizations use custom templates. They would need to adjust these themselves.

**Comment by bjendres** [comment]
> [...] so the copy would have to show data as it would when created on the date the original was issued

Yes, I agree, see above. (I edited the comment after first submission, in case you're answering to an email)

**Comment by MarcMichalsky** [comment]
Should I submit a PR with my suggested fixes or do you want to apply them quickly yourself?

**Comment by bjendres** [comment]
> Should I submit a PR with my suggested fixes or do you want to apply them quickly yourself?

Yes, please. We like PRs :)

**Comment by jensschuppe** [comment]
Also, your commits: your laurels, @MarcMichalsky! :1st_place_medal:
