### ISSUE TITLE
Donrec disables scheduled jobs being triggered

### ISSUE THREAD

**Issue by MichPoe** [systopia/de.systopia.donrec#182]
Salut. Since a few civicrm versions, we need to turn off the donrec extension because once it is turned on, cron stops triggering jobs. The log shows:

Oct 11 11:32:05 | [warning] Deprecated function CRM_Core_BAO_Job::retrieve, use API.
-- | --

I tried to disable other civicrm extensions in case there is an interference. But nothing changed.
What could cause this problem?

<img width="1302" alt="Bildschirmfoto 2023-10-11 um 12 09 32" src="https://github.com/systopia/de.systopia.donrec/assets/42148217/dae6b18c-86f2-4200-ab3e-8556ea5a645b">
<img width="1309" alt="Bildschirmfoto 2023-10-11 um 12 09 40" src="https://github.com/systopia/de.systopia.donrec/assets/42148217/ce58f48e-46ff-47c0-aaf5-e33f83703f13">

**Comment by MichPoe** [comment]
p.s: newest civicrm update 5.65.2 and donrec 2.3-dev

**Comment by jensschuppe** [comment]
I can't imagine a deprecated method call causing cron to stop working. Also, this method is not being called by the extension at all. Are there any other error messages logged (ideally with a stack trace)?

Would you be able to provide the exact version/commit of the extension you're using? `2.3-dev` is not a tagged version and refers to the current `master` branch, where quite some things have happened since the last stable version.

**Comment by MichPoe** [comment]
Thank you. I reverted back to the recently released stable version 2.2.1 but still having the same problem (scheduled jobs not triggering after the install of donrec). I could find following log info (not many errors created as such):

admin.php?page=CiviCRM&q=civicrm%2Fadmin%2Flogviewer
[Mon Oct 16 11:16:05.530111 2023] [php7:warn] [pid 108482] [client 104.28.130.5:37651] PHP Warning:  chmod(): Operation not permitted in /srv/www/html/wordpress/wp-includes/class-wp-image-editor-gd.php on line 509
[Mon Oct 16 11:16:09.668009 2023] [php7:warn] [pid 111703] [client 54.36.148.249:35975] PHP Warning:  chmod(): Operation not permitted in /srv/www/html/wordpress/wp-includes/class-wp-image-editor-gd.php on line 509
[Mon Oct 16 11:16:20.023970 2023] [php7:warn] [pid 108482] [client 104.28.130.5:37651] PHP Warning:  chmod(): Operation not permitted in /srv/www/html/wordpress/wp-includes/class-wp-image-editor-gd.php on line 509
[Mon Oct 16 11:16:33.209636 2023] [access_compat:error] [pid 107731] [client 107.180.103.21:40324] AH01797: client denied by server configuration: /srv/www/html/wordpress/wp-login.php
[Mon Oct 16 11:16:33.741345 2023] [access_compat:error] [pid 107906] [client 107.180.103.21:40430] AH01797: client denied by server configuration: /srv/www/html/wordpress/wp-login.php
[Mon Oct 16 11:16:34.274441 2023] [access_compat:error] [pid 83474] [client 107.180.103.21:40548] AH01797: client denied by server configuration: /srv/www/html/wordpress/xmlrpc.php

**Comment by jensschuppe** [comment]
Sorry, but those log messages do not seem to be related to this extension.

**Comment by MichPoe** [comment]
I know, there are no other error messages and therefore no way for us to find a hint for a solution. We can only disable and abandon the extension at this point. Thanks anyway for your replies.

**Comment by jensschuppe** [comment]
Sorry we couldn't help from here. If you're interested, feel free to send an inquiry to info@systopia.de for contracting us with debugging etc.

**Comment by MichPoe** [comment]
NEW:When triggering the cron manually, I get following error information, maybe helpful.
PHP Parse error: syntax error, unexpected '=' in /srv/www/html/wordpress/wp-content/plugins/files/civicrm/ext/de.systopia.donrec/donrec.php on line 285

All the best, Michael

**Comment by jensschuppe** [comment]
This line contains the NULL-coalescing assignment operator `??=` which has been introduced with PHP 7.4. If you encounter a syntax error, you are most likely on a PHP version older than 7.4 and should update your PHP version to a more recent one. PHP 7 has been End-Of-Life for over a year now, so you should update to version 8.1. or 8.2 at least.
