### ISSUE TITLE
Problems with Epiphany browser

### ISSUE THREAD

**Issue by bjendres** [systopia/de.systopia.donrec#22]
A user reports that his Epiphany browser (version 3.4.1) has trouble with some of the JS elements. We recommend using Firefox, but we will fix this if there is a need for this.

**Comment by systopia** [comment]
This might be related to (and fixed with) #37.

Could anyone test this with 1.4.beta1?

**Comment by jensschuppe** [comment]
Closing, since there's been no feedback and the (possibly) related fix in #37 has been released since 1.4.
