### ISSUE TITLE
Edit contribution - change amount doesn't work properly

### ISSUE THREAD

**Issue by Detsieber** [systopia/de.systopia.donrec#25]
When I try to change an amount for an existing contribution, CiviCRM won't save and gives the error message: 
"The sum of fee amount and net amount must be equal to total amount"
In fact, when adjusting the net amount to the new total, the contribution can be saved again.
(I could imagine, this is a regression from the latest change - at least I did not see that before).

**Comment by systopia** [comment]
I have observed this issue before, and as far as I know it's rather a problem with the later 4.4.x versions of CiviCRM. 

@Detsieber :Which version are you using?

**Comment by Detsieber** [comment]
This happens with 4.6.9


Am 02.12.2015 um 08:52 schrieb SYSTOPIA:

**Comment by systopia** [comment]
Could you make sure, that the same thing doesn't happen with the donation receipts extension disabled?

**Comment by Detsieber** [comment]
I am sorry for having created some trouble: After deactivating the
donrec extensions, the error still persists.
The error also persists on another civicrm install, where the donrec
extension never had been installed.

However, another civicrm running on 4.6.10, doesn't behave this way. And
I had never seen that before...

**Comment by systopia** [comment]
No problem.
