### ISSUE TITLE
Feature request: Search for contributions with / without donation receipts

### ISSUE THREAD

**Issue by Detsieber** [systopia/de.systopia.donrec#26]
It should be possible to search for contributions, for which already a donation receipt is issued (or: not issued), via the UI.

**Comment by systopia** [comment]
It is. There is an accordion wrapper in the contribution search form. On my system it's right underneath the 'Recurring Contributions' one.

@Detsieber: Could you confirm this?

**Comment by Detsieber** [comment]
I can confirm this!
However, there lacks a functionality to search for contributions _without_ a donation receipt.

As a workaround, one could search for contacts with donation receipts, and exclude this group from another group consisting of all contacts with a contribution. But that's pretty complicated and still doesn't help for the case, when somebody received some but not all donation receipts.

However, this is a feature request of moderate importance, since there is another simple workaround for the business requirement (by creating bulk donation receipts for all open contributions).

**Comment by systopia** [comment]
Great.
