### ISSUE TITLE
Settings Page: location type translation quirks

### ISSUE THREAD

**Issue by ghost** [systopia/de.systopia.donrec#27]
The file [CRM/Admin/Form/Setting/DonrecSettings.php](https://github.com/systopia/de.systopia.donrec/blob/master/CRM/Admin/Form/Setting/DonrecSettings.php#L29-L33) contains a code snippet that pulls all available location types and displays their translated _names_ in a select box. This solution is quite prone to errors, as we have recently discovered.

In this case the string "home" got translated to "CiviCRM Startseite" (CiviCRM Homepage), because someone added the string to transifex. The optimal solution for the current and future versions of CiviCRM would be to remove the ts()-tag and return labels instead of names.

**Please note**: We are **NOT** implementing this proposed change right now, because it would break compatibility with older CiviCRM-versions (<4.5 afaik) because these versions contain a bug, where CiviCRM takes labels of location types instead of their values and uses them for queries, lookups etc.

**Comment by jensschuppe** [comment]
This seems outdated, can't reproduce.
