### ISSUE TITLE
Changes in civicrm_setting? => no field "group_name"

### ISSUE THREAD

**Issue by mielert** [systopia/de.systopia.donrec#33]
I've deinstalled 1.2.1 and installed 1.3 beta on 4.7.8.
I can't access the settings probably because of changes in civicrm_settings.

DB Error: no such field", -19, 16, (Array:2), "SELECT name FROM civicrm_setting WHERE group_name = 'Donation Receipt Profile...")

**Comment by systopia** [comment]
I'm strongly suspect that you tried that with CiviCRM 4.7, which the extension is not compatible with atm (see https://github.com/systopia/de.systopia.donrec/issues/34).

@mielert: Could you confirm that?

The culprit most likely is this line https://github.com/systopia/de.systopia.donrec/blob/1.3.beta1/CRM/Donrec/Logic/Profile.php#L126, which has already been flagged.

**Comment by mielert** [comment]
@systopia Yes, I tried it with 4.7.8 as I wrote. Just to give you feedback.
Probably "Civi::settings()->get('max_attachments');" (https://wiki.civicrm.org/confluence/display/CRMDOC/Settings+Reference#SettingsReference-SettingsRetrieval) will do the job.

**Comment by systopia** [comment]
I'm not sure how ``Civi::settings()->get('max_attachments');`` would fix the problem here. If you could create a pull request, we'll have a look.

**Comment by mielert** [comment]
I've never worked with pull requests by now and don't have time to learn it.

This function seems to work:

  /**
   * return all existing profiles
   *
   * @return array(name => name)
   */
  public static function getAllNames() {
    $allProfiles = Civi::settings()->get(self::$SETTINGS_PROFILE_GROUP); // FritzMielert
    if (empty($allProfiles)) {
      $allProfiles['Default'] = 'Default';
    }
    return $allProfiles;
  }

**Comment by systopia** [comment]
Thanks, I included this into ``dev_33`` (https://github.com/systopia/de.systopia.donrec/tree/dev_33).

@mielert: Could you verify that this works - of course also when you're using profiles?

**Comment by mielert** [comment]
@systopia something is still broken, sorry.
When just using the profile Default it works but

When replacing the function above with the following lines I can generate donation receipts in 4.7 for the first time:
```
  /**
   * check if a profile of the given name exists
   */
  public static function exists($profile_name) {
    $params = array(
      'name' => $profile_name,
      'group' => self::$SETTINGS_PROFILE_GROUP,
    );
    try{
      $result = civicrm_api3('Setting', 'getvalue', $params);
    }    
    catch (CiviCRM_API3_Exception $e) {
      // Handle error here.
    }
    return $result;
  }
```

**Comment by systopia** [comment]
Thanks, we'll address and test this when doing the 4.7 compatibility. Most likely this is going to be version 1.4

**Comment by mielert** [comment]
btw: Applying both changes in 1.3 I'm still able to generate receipts in Firefox.
