### ISSUE TITLE
Staging.php: Missing information about clicked buttons

### ISSUE THREAD

**Issue by mielert** [systopia/de.systopia.donrec#37]
The send buttons that have been clicked are not transferred via post form.
This error does only show up in Safari.

Dump of $_REQUEST

```
(
    [q] => civicrm/donrec/task
    [sid] => 1
    [ccount] => 
    [origin] => 
    [donrec_type] => 1
    [result_type] => PDF
    [IDS_request_uri] => /index.php?q=civicrm/donrec/task&sid=1&ccount=&origin=
    [IDS_user_agent] => Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_5) AppleWebKit/601.6.17 (KHTML, like Gecko) Version/9.1.1 Safari/601.6.17
)
```

CiviCRM 4.7.8 
Part of #34 ?

**Comment by systopia** [comment]
> The send buttons that have been clicked are not transferred via post form.

@mielert  I'm not sure which buttons you're talking about, could you add a screenshot?

(sorry for the late response, I was on holiday)

**Comment by mielert** [comment]
In Safari nothing happens, no matter which of the following three buttons I click. The page is just reloaded. <img width="794" alt="bildschirmfoto 2016-09-06 um 13 22 40" src="https://cloud.githubusercontent.com/assets/937362/18271910/1317f3d2-7435-11e6-8063-b29345fe2824.png">
But these buttons are essential to generate the files.

Clicking test run in Safari
```
Var Name                     Var Content       Var Empty?      Var Set?
_REQUEST['donrec_abort']                       empty           not set
_REQUEST['donrec_testrun']                     empty           not set
_REQUEST['donrec_run']                         empty           not set
```
Clicking test run in Firefox
```
Var Name                     Var Content       Var Empty?      Var Set?
_REQUEST['donrec_abort']                       empty           not set
_REQUEST['donrec_testrun']   Testlauf          not empty       set
_REQUEST['donrec_run']                         empty           not set
```

**Comment by mielert** [comment]
Here's some kind of a bugfix for Staging.tpl:

Modified onClick
```
  {if $statistic.status != 'DONE'}
    <input name="donrec_testrun" onClick="submit_form(this.attributes["name"].value);" value="{ts domain="de.systopia.donrec"}Test run{/ts}" class="form-submit" type="submit">
  {/if}
  <input name="donrec_run" onClick="submit_form(this.attributes["name"].value);" value="{ts domain="de.systopia.donrec"}Issue donation receipt(s){/ts}" class="form-submit" type="submit">
  <input name="donrec_abort" onClick="submit_form(this.attributes["name"].value);" value="{ts domain="de.systopia.donrec"}Abort{/ts}" class="form-submit" type="submit">
```

Modified submit_form
```
// and provide a function to go around it
function submit_form(button_name) {
  window.onbeforeunload = null;
  cj('#stagingform').submit();
}
```

I don't get it why it's enough just to call the attribute "name" to transfer it. But by no that works. Any ideas?

**Comment by systopia** [comment]
Hi @mielert, thanks for your input. I have to tell you that your fix didn't work - it actually caused a JS error that would then abort the custom submission process. And the fallback default submission process then worked for you :)

However, thanks a lot for pointing me in the right direction; I think I fixed it with https://github.com/systopia/de.systopia.donrec/commit/fe56c90a4f181c2061e453150dd53c15aaf4272b, and it should be released with the next version.

**Comment by mielert** [comment]
Thanks a lot!
Your fix works in Safari 10.

**Comment by systopia** [comment]
Great, thanks for testing!
