### ISSUE TITLE
Missing tokens for addressee and greeting fields

### ISSUE THREAD

**Issue by thomst** [systopia/de.systopia.donrec#44]
There are tokens which are saved to the receipt-table, but not loaded when creating receipts:
* contributor.postal_greeting_display
* contributor.email_greeting_display
* maybe others

**Comment by kenleegit** [comment]
In my case only {$contributor.display_name} gets displayed. All other tokens address lines, city, country etc are all missing.

**Comment by systopia** [comment]
@kenleegit: Are the fields ``NULL`` in the database (``civicrm_value_donation_receipt_x`` table) or only as a Smarty tokens?

**Comment by jensschuppe** [comment]
The `{$contributor.addressee_display}` token value is also missing. The values are being stored to the database but not received when building token values.

Scanning `CRM_Donrec_Logic_Receipt::getAllTokens()`, those three were the only ones missing.
