### ISSUE TITLE
Profiles disappear when updating from 1.3 to 1.4

### ISSUE THREAD

**Issue by thomst** [systopia/de.systopia.donrec#45]
I had two customized profiles. The default profile were deleted.
After updating the extension from 1.3 to 1.4 the customized profiles were gone. Instead the default-profile was found.

This happend on a 4.6.24 and a 4.7.20 CiviCRM-Installation

**Comment by systopia** [comment]
That's true. In order to make it compatible with 4.7 we had to completely rework the profiles. There is some code that should transform them but it doesn't seem to be reliable.

**Comment by jensschuppe** [comment]
This seems outdated.
