### ISSUE TITLE
Support Polish language in converting number to words

### ISSUE THREAD

**Issue by scardinius** [systopia/de.systopia.donrec#46]
Hi @systopia

Thank you for donrec! 

I'd like to add supporting Polish in `totaltext` variable. My assumptions:

* converting based on repo https://bitbucket.org/stopsopa/kwotaslownie
* language is determined by locale of civicrm `$_SESSION['CiviCRM']['lcMessages']`. This is Default Language from "Localization > Languages, Currency, Locations"
* German is default language

What do you think about such solution?

**Comment by systopia** [comment]
Hi @scardinius! Looks good, I'll include that into the next release. But Shouldn't we include ``packages/kwotaslownie``, though?

**Comment by systopia** [comment]
see #50

**Comment by systopia** [comment]
Hi @scardinius! I included your code (somwhat refactored) into ``1.7-alpha1``. Let m know whether it works for you

**Comment by bjendres** [comment]
We'll just assume that it works ;-)

Just create a new ticket if it doesn't...
