### ISSUE TITLE
Settings should be in in pull-down menu (was: Address lines are not shown)

### ISSUE THREAD

**Issue by kenleegit** [systopia/de.systopia.donrec#47]
On 1.4 and 1.5 beta, Drupal 7.56, PHP 5.6.31, CiviCRM 4.7.20 and 4.7.24.

Receipt shows only contributor's display name. All other information, such as address are not shown.
The respective columns at receipt table have only NULL values.

I tried to troubleshoot myself (sorry for being a beginner), but cannot find which code went wrong.
Thank you.

**Comment by kenleegit** [comment]
I kinda found out the solution.
At CRM/Donrec/Logic/Profile.php, function defaultProfileData()
287,290c287,290
<       'legal_address'           => 0,  // '0' is the primary address
<       'postal_address'          => 0,
<       'legal_address_fallback'  => 0,
<       'postal_address_fallback' => 0,
---
>       'legal_address'           => array('0'),  // '0' is the primary address
>       'postal_address'          => array('0'),
>       'legal_address_fallback'  => array('0'),
>       'postal_address_fallback' => array('0'),

On the other hand, I do not see "Donation Receipts Settings" in the administration console in "CiviContribute", as described on the wiki page. All I have is the "Default" profile. If you can, please advise on this.

**Comment by systopia** [comment]
>  I find that "Donation Receipts Settings" appears only at Admin Consol [...] Please put the settings accessible from pull-down, if possible. Thank you.

Hi @kenleegit. This is done on purpose, we didn't want to overload the pull-down menu. However, if we get a couple of ``+1``s here, I'll be happy to change that.

**Comment by jensschuppe** [comment]
Since this issue addresses putting the extension settings in the navigation menu and there haven't been any `+1`s for that, I'm closing the issue.
