### ISSUE TITLE
International number_to_words function

### ISSUE THREAD

**Issue by bjendres** [systopia/de.systopia.donrec#50]
There should be a plug-in like system to add other languages.

@sluc23 I understand you create something like this in IXIAM, could you create a PR or point me to the right code?

**Comment by sluc23** [comment]
@systopia 

1. https://github.com/ixiam/de.systopia.donrec/blob/master/CRM/Donrec/Logic/ReceiptTokens.php#L171
2. https://github.com/ixiam/de.systopia.donrec/blob/master/CRM/Utils/DonrecHelper.php#L23
3. https://github.com/ixiam/de.systopia.donrec/blob/master/CRM/Utils/DonrecLang.php#L19
4. https://github.com/ixiam/de.systopia.donrec/tree/master/CRM/Utils/Lang

**Comment by sluc23** [comment]
Hi @systopia , still interested in including "numbers to words" in different languages?
In that case we could work on updating and rebasing our fork and trying to PR these changes

**Comment by systopia** [comment]
Hi @sluc23, yes, still interested, but too busy atm. Also, I'm on holiday now, but I'll try and pick this up in January. Season's greetings!

**Comment by sluc23** [comment]
sure.. let's get back to this in January, when starts the high season for Donor Receipts :)
Happy holidays to you, and for all **de.systopia.donrec** users :santa:

**Comment by systopia** [comment]
@sluc23 / @scardinius : I have merged your respective approaches into a new data structure with ``1.7-alpha1``. You now have a "Language" setting which currently supports EN, DE, PL and ES.

Could you please have a look if it that works for you?

**Comment by sluc23** [comment]
thanks @systopia ! 
yes definitely will take a look in upcoming days, we are looking forwards to merge all code from our fork and start using this main extension.

cc: @rubofvil, @CsarRamos

**Comment by jensschuppe** [comment]
@bjendres The implementation for German needs some improvements, e.g. no spaces between each part of composed numbers like "ein hundert zwei und siebzig", which should be "einhundertzweiundsiebzig" - maybe as a separate issue?

**Comment by bjendres** [comment]
@jensschuppe I don't think everybody would agree to that. Definitely create an extra ticket, and get some customer opinions.... I vaguely remember there being a discussion about this when we implemented this.

**Comment by bjendres** [comment]
Released with ``1.7``
