### ISSUE TITLE
Select year relevant for ID generator

### ISSUE THREAD

**Issue by bjendres** [systopia/de.systopia.donrec#51]
If you generate receipts for the last year, the current year is used for the ID generation. This might be intended in some scenarios, but unexpected in others.

We want to have a new ID generator token ``contribution_year`` that is the (maximum) year of the contribution(s).

**Comment by sluc23** [comment]
@systopia 

1. https://github.com/ixiam/de.systopia.donrec/commit/d5e944de04eb92d0a5723e3d591a920c021716fe
2. https://github.com/ixiam/de.systopia.donrec/commit/af1e3bafc3f405bf89e702f944117a9dbc4a44e6

**Comment by rubofvil** [comment]
We tested, and works property.

**Comment by bjendres** [comment]
Great, thanks! We'll wait for ``1.7`` to be released, and then merge it into ``1.8``
