### ISSUE TITLE
Contribution receipts lost when merging contacts

### ISSUE THREAD

**Issue by Fabian-SYSTOPIA** [systopia/de.systopia.donrec#53]
Tested under CiviCRM 4.7.30 and 4.7.29, DonationReceipt 1.4 and 1.5beta2

Reproduction: Merge two contacts with one or more receipts each using CiviCRM's merge function via the UI or API.

Receipts previously attached to contact A are lost even though the boxes to merge them were checked.

**Comment by systopia** [comment]
This is not an issue with the donation receipts extension, the reason is [CRM-21773](https://issues.civicrm.org/jira/browse/CRM-21773). I have already created a patch that is currently being tested. Hopefully it will be merged into core soon.
