### ISSUE TITLE
DB Error: no such table

### ISSUE THREAD

**Issue by jensschuppe** [systopia/de.systopia.donrec#58]
Instead of doing things like `SELECT [...] FROM civicrm_value_donation_receipt_item_%d` and `$table = "civicrm_value_donation_receipt_item_$group_id";`, retrieve the table name for the custom group via an API call, as the table name may be truncated (assuming multi language being a candidate scenario) resulting in CiviCRM fataling with "DB Error: no such table".

**Comment by systopia** [comment]
released with ``1.6-beta1``
