### ISSUE TITLE
WP: URL-scheme falling back to Drupal URL-scheme while generating receipts and breaks link for zip-file download

### ISSUE THREAD

**Issue by pf030** [systopia/de.systopia.donrec#60]
Under Wordpress with CiviCRM 4.7x and higher we have encountered the following problem:

In step 2 of the assistant (for generating the donations receipts) **the URL-scheme of Wordpress-installations breaks** (visible also in missing styles and CiviCRM menu) **and falls back to the Drupal URL-scheme**. 

**The assistant completes, but** this behaviour results in a broken link for downloading the ZIP-file containing the generated donation receipts.

**Example:**

**Wordpress URL-scheme** in step 2 of the assistant for generating donation receipts **should be**:
https://civicrm.domain/wp-admin/admin.php?page=CiviCRM&q=civicrm/donrec/runner&sid=2&bulk=0&final=1&exporters=PDF

But it **falls back to Drupal URL-scheme**:
https://civicrm.domain/civicrm/?page=CiviCRM&q=civicrm/donrec/runner&sid=2&bulk=0&final=1&exporters=PDF

**Despite it's possible** to get the ZIP-file containing the donation receipts in the last step of the assistant by manually copying, editing the download-link to Wordpress URL-scheme and pasting it to the browser, this is **very uncomfortable** when generating lots of donation receipts and of course **not a fail-safe workaround for non-admin users**.

We can confirm this behaviour on a live system as well as on a clean test installation in the above mentioned environment.

**We suspect it's a bug** and request testing and fixing by the developers as the extension was released as "CRM-native".

Can anyone confirm?

Could the developers have a look on it please?

**Comment by systopia** [comment]
Thanks for reporting @pf030

**Comment by Detsieber** [comment]
I can confirm the described behaviour (CiviCRM 5.16.1, Donation Receipts 1.7).

There are two workarounds: 
1) Copy and edit the download link (replace "/civicrm/?page" with "/wp-admin/admin.php/?page")
2) Make donrec save the pdf files (in donrec-settings), then download the created pdf-file using the donrec tab at the contact.

However, this better should be fixed. Should not be a big thing, and I could help out with a Wordpress/CiviCRM install. SfE might provide funding.

**Comment by Detsieber** [comment]
I tested with this patch - and it works well!
However, this commit is not contained in Release 1.8...
@jensschuppe @bjendres Could you please release that?

Best
Detlev

**Comment by jensschuppe** [comment]
This is scheduled to be released with an intermediate release 1.8.1, along with some other issues (also wordpress-related); see [milestone](https://github.com/systopia/de.systopia.donrec/milestone/10).

**Comment by jensschuppe** [comment]
released with [1.8.1](https://github.com/systopia/de.systopia.donrec/releases/tag/1.8.1).
