### ISSUE TITLE
WP: namespace for tokens used in donation receipts-templates not available

### ISSUE THREAD

**Issue by pf030** [systopia/de.systopia.donrec#62]
Under Wordpress with CiviCRM 4.7x and higher we have encountered the following problem:

**The Smarty variables from the namespace of the extension ($contributor.xxx) are not available/filled when generating donation receipt PDFs. This makes the extension unusable under the mentioned environement.**

**We suspect it's a bug.**

Can anyone confirm?

Could the developers have a look on it please?

**Comment by systopia** [comment]
Thanks for reporting @pf030 

We don't have any client using the extension on Wordpress, sorry.

@all: can anyone confirm this?

**Comment by jensschuppe** [comment]
We could not reproduce this, so closing.
