### ISSUE TITLE
Notices on settings screen

### ISSUE THREAD

**Issue by eileenmcnaughton** [systopia/de.systopia.donrec#64]
I downloaded the extension & loaded the setting screen on master (5.8) to check if recent changes in core would mess with it (https://github.com/civicrm/civicrm-core/pull/13048) - it seemed OK but I did observe some other notices so posting s/shot here

![screenshot 2018-11-01 21 15 12](https://user-images.githubusercontent.com/336308/47840532-71d3f680-de1b-11e8-8837-4eb528582ff9.png)

**Comment by systopia** [comment]
Thanks for the heads-up @eileenmcnaughton!

**Comment by jensschuppe** [comment]
This will be taken care of in #92.

**Comment by bjendres** [comment]
Released with ``2.0``
