### ISSUE TITLE
PHP 7.1/7.2 Compatibility

### ISSUE THREAD

**Issue by systopia** [systopia/de.systopia.donrec#65]
We should make sure the extension is compatible with PHP ``7.1`` and ``7.2``

**Comment by jensschuppe** [comment]
1c33ffc170586cd83a37af3f9b3e143daf20ef52 is the only thing PHPStorm's Language Level inspection reported as being incompatible with PHP 7.2.

**Comment by systopia** [comment]
released with ``1.6-beta1``
