### ISSUE TITLE
ArgumentCountError when calling CRM_Donrec_Logic_Receipt::createCopy()

### ISSUE THREAD

**Issue by jensschuppe** [systopia/de.systopia.donrec#66]
`CRM_Donrec_Logic_Receipt::createCopy()` is being called without parameters in `civicrm_api3_donation_receipt_copy()` and causes an `ArgumentCountError`.

Looking at the method, the parameter `&$parameters` is never used and the method is only being called from that single code point. The signature should be adapted to not require any parameter.

Thanks to @thomst for initial reporting.

**Comment by jensschuppe** [comment]
c837535387283e921e514ddc15b815e004a377b2 is a patch commit for Version 1.3 on branch [dev_66_1.3](https://github.com/systopia/de.systopia.donrec/tree/dev_66_1.3) which is not to be merged into master.

**Comment by systopia** [comment]
released with ``1.6-beta1``
