### ISSUE TITLE
MySQL queries not compatible with ONLY_FULL_GROUP_BY mode

### ISSUE THREAD

**Issue by jensschuppe** [systopia/de.systopia.donrec#67]
Several queries in the extension are not compatible with the MySQL `ONLY_FULL_GROUP_BY` mode, which is enabled by default starting with MySQL 5.7.5<sup>[1][mysql-release-notes]</sup>

Those queries use aggregation (with functions like `COUNT()`, `SUM()`, etc. or with a `GROUP BY` clause) but do not include all fields in the `SELECT` clause in the grouping.

If MySQL is running in `ONLY_FULL_GROUP_BY` mode, the extension is not usable and crashes with an "Unknown DB error" (e.g. when creating donrec snapshots).

Next steps:

1. Identify affected queries
2. Try to fix them by:
    - including all columns in the grouping, or
    - rework the query logic
    - use `ANY_VALUE()` aggregation function to keep MySQL's current (undefined) value selection

[mysql-release-notes]: https://dev.mysql.com/doc/relnotes/mysql/5.7/en/news-5-7-5.html#mysqld-5-7-5-sql-mode "MySQL 5.7.5 release notes"

**Comment by jensschuppe** [comment]
We try to use `ANY_VALUE()` to make sure the current behavior ist being kept.

**Comment by jensschuppe** [comment]
`ANY_VALUE()` is not available in MariaDB, so this is not a correct fix. Using `CRM_Core_DAO::disableFullGroupByMode()` and `CRM_Core_DAO::reenableFullGroupByMode()` instead is what CiviCRM core is doing, until those queries are being reworked to meet standard.

**Comment by bjendres** [comment]
Released with ``2.0``
