### ISSUE TITLE
Provide presets for watermarks in the receipt template (was: Watermark should be placed on all PDF pages)

### ISSUE THREAD

**Issue by jensschuppe** [systopia/de.systopia.donrec#68]
The watermark is only visible on the first PDF page, but must be placed on all pages for copies and drafts.

**Comment by jensschuppe** [comment]
a1bfefa816e9dca64a393556230ec7bbcc2282ff Uses an SVG background image on the `BODY` element for placing the watermark on all pages. This, however, only works with wkhtmltopdf.

For dompdf, the current behaviour is being retained.

@systopia This would need some real-world testing with different templates.

**Comment by systopia** [comment]
@jensschuppe: As discussed, we'll create (hard)coded presets:
1. DomPDF traditional
2. wkhtml2pdf traditional
3. new svg based, big font size
4. new svg based, smaller font size
5. upper right corner

**Comment by jensschuppe** [comment]
@systopia This is ready for review.

**Comment by jensschuppe** [comment]
The latest commits use the paper size dimensions fpr sizing the `BODY` and `SVG` element to prevent watermarks moving out of the printable area.

Also added a new preset "SVGHolohedral" that prints the watermark 10 times per line, repeatedly across the whole document.

@systopia Could you try and test that?

**Comment by systopia** [comment]
released with ``1.7``
