### ISSUE TITLE
Cancel donation receipts is broken

### ISSUE THREAD

**Issue by Detsieber** [systopia/de.systopia.donrec#70]
After Update to CiviCRM 5.9.0, donrec 1.5, PHP 7.1, cancellation of donation receipts isn't working anymore:
Silent error, nothnig happens.

The drupal watchdog shows the following error:

> Type | php
> Location | https://domain.org/civicrm/ajax/rest
> Referrer | https://domain.org/civicrm/contact/view?reset=1&cid=5&selectedChild=donation_receipts
> message | ArgumentCountError:  Too few arguments to function CRM_Donrec_Logic_Receipt::setStatus(), 1  passed in  /html/sites/default/files/civicrm/ext/de.systopia.donrec/api/v3/DonationReceipt.php  on line 27 and exactly 2 expected in CRM_Donrec_Logic_Receipt->setStatus() (line 231 of /html/sites/default/files/civicrm/ext/de.systopia.donrec/CRM/Donrec/Logic/Receipt.php).
> Severity | error
> 

Workaround: Deletion of donation receipt is working...

**Comment by jensschuppe** [comment]
https://github.com/systopia/de.systopia.donrec/blob/7b9721c6b593e7a5f7b4bd69af3600617a9b76fb/CRM/Donrec/Logic/Receipt.php#L224-L229

The docblock and method signature indicates that the `&$parameters` argument is not used for anything yet and should be removed or given a default value, similar as in c837535387283e921e514ddc15b815e004a377b2.

@systopia Can you confirm this is the way to go?

**Comment by bjendres** [comment]
@jensschuppe Wasn't this released with ``1.6``?

**Comment by jensschuppe** [comment]
Correct, therefore closing.

**Comment by bjendres** [comment]
released with ``1.6``
