### ISSUE TITLE
Wrong value for {$receipt.total} template variable in bulk receipt e-mail template

### ISSUE THREAD

**Issue by jensschuppe** [systopia/de.systopia.donrec#71]
When sending bulk receipts via e-mail, the value for the `{$receipt.total}` template variable is not correct. Instead of the sum of all donations being receipted, it *seems* to be set to the value of the first processed donation within that bulk receipt.

**Comment by jensschuppe** [comment]
@systopia This is a first approach on passing bulk receipt tokens into the e-mail template instead of only the first snapshot line. There's some more interference, as denoted with `TODO`s, but I'm not really familiar with the snapshot model - maybe that's not the correct way to do it ...?

**Comment by jensschuppe** [comment]
Should be checked for backwards compatibility (i.e. merge current tokens with "new" ones).

**Comment by jensschuppe** [comment]
Merged "new" tokens with the existing ones inside `{$receipt}`.

<details>
<summary>Template variables being overwritten to account for all contribtuons being receipted:</summary>

- status
- total_amount
- non_deductible_amount
- date_from
- date_to
- id
- profile
- contact_id
- currency
</details>

<details>
<summary>Template variables being added:</summary>

- receipt_id
- issued_on
- issued_by
- lines[id]
    - id
    - receive_date
    - contribution_id
    - total_amount
    - non_deductible_amount
    - financial_type_id
    - financial_type
- contributor
  - id
  - contact_type
  - display_name
  - addressee_display
  - postal_greeting_display
  - email_greeting_display
  - street_address
  - postal_code
  - city
  - country
  - supplemental_address_1
  - supplemental_address_2
  - addressee
- addressee
  - street_address
  - postal_code
  - city
  - country
  - supplemental_address_1
  - supplemental_address_2
  - display_name
  - addressee
  - addressee_display
- issued_by_display_name
- today
- total
- totaltext
- totalmoney
- items[id]
    - id
    - receive_date
    - contribution_id
    - total_amount
    - non_deductible_amount
    - financial_type_id
    - financial_type
- organisation
  - street_address
  - postal_code
  - city
  - country
  - supplemental_address_1
  - supplemental_address_2
  - display_name
  - addressee
- watermark
</details>

**Comment by systopia** [comment]
released with ``1.6-beta1``
