### ISSUE TITLE
"Send via E-Mail" broken in 1.6-beta1

### ISSUE THREAD

**Issue by systopia** [systopia/de.systopia.donrec#73]
Due to a code change aiming at fixing #71, the "Send via E-Mail" export is fundamentally broken. **Don't use!**

**Comment by jensschuppe** [comment]
2eb565af6a4be48094997122cabbe5ae2c5f71db fixes a remaining variable, which however, seems to only have an impact on test mode output.

With the fixes in this issue, e-mails are being sent to the correct contacts again - I refer to the test mode output here, which states that e-mails would be sent to the particular contacts - whereas without these fixes, the test mode output states e-mails would all be sent to the same contact.

**Comment by systopia** [comment]
fixed with ``1.6-beta2``
