### ISSUE TITLE
German number_to_words function - remove spaces in cardinal numbers

### ISSUE THREAD

**Issue by jensschuppe** [systopia/de.systopia.donrec#78]
Follow-up for #50:

The number_to_words implementation for German needs some improvements, e.g. no spaces between each part of composed numbers like "ein hundert zwei und siebzig", which should be "einhundertzweiundsiebzig".

See [Wikipedia](https://de.wikipedia.org/wiki/Zahlwort#Bildung_der_Kardinalzahlen_im_Deutschen) for reference on how to build cardinal number numerals.

**Comment by bjendres** [comment]
We should get some customer opinions.... I vaguely remember there being a discussion about this when we implemented it this way.

**Comment by jensschuppe** [comment]
There's at least one customer who requested that directly (and may supply funding), which is why I came up with the comment on the other issue in the first place.

Also, it is just wrong to have the spaces in there. See the [Duden](https://www.duden.de/sprachwissen/sprachratgeber/Schreibung-von-Zahlen) as another official reference.

**Comment by bjendres** [comment]
> There's at least one customer who requested that directly (and may supply funding), which is why I came up with the comment on the other issue in the first place.

I meant from the people already using it...before we change their behaviour without them noticing. Maybe we can keep both formats - the old one as "legacy/wrong" :)

**Comment by jensschuppe** [comment]
Sure. Although I would not introduce a new setting, but inject the legacy format as a separate token `{$totaltext_legacy}` or the like, only available for German, to keep it as clean as possible - and let people decide to alter their templates or not when they update the extension.

**Comment by jensschuppe** [comment]
Discussed we'll do a separate language setting "German (with spaces)" and "German (without spaces)".

**Comment by jensschuppe** [comment]
This looks good so far and got signoff from the customer who requested it, thus merged and closing.
