### ISSUE TITLE
Create donation_receipt_tokens hook

### ISSUE THREAD

**Issue by bjendres** [systopia/de.systopia.donrec#79]
Sometimes people need additional tokens in the donation receipt. These tokens would not be stored in the receipt, and therefore would differ in the copy, so that shouldn't be part of the main extension.

In order to enable people to add tokens anyway, we would want to add a hook.

**Comment by rubofvil** [comment]
I tested the hook, and works fine, thanks for the work. Have you planned make the merge to master?

**Comment by sluc23** [comment]
we tested this and works fine. Do you want us to make a PR?

**Comment by sluc23** [comment]
hi @bjendres , any plans on merging and realising this changes in a new version soon?

**Comment by bjendres** [comment]
@sluc23: Yes, will release 1.7 soon and merge this into ``master``, i.e. it will eventually be released in ``1.8``
