### ISSUE TITLE
When editing a profile, email settings get applied to all profiles

### ISSUE THREAD

**Issue by Fabian-SYSTOPIA** [systopia/de.systopia.donrec#85]
Tested on version Donrec Version 1.7 stable and CiviCRM Version 5.14.0 and 5.10.0 (both Drupal 7.67). 

When editing a profile (civicrm/admin/setting/donrec) all the settings regarding emails seem to be applied to ALL profiles. Steps to recreate:

1. Create a profile "test1" select an email template and save
2. Create another profile "test2" select a different email template and save

The email template selected in "test2" will be applied to the profile "test1" as well (that may affect other settings too"

**Comment by jensschuppe** [comment]
This is intended behavior, only the settings in the first fieldset are considered to be profile-dependent. @bjendres correct me if I'm wrong.

**Comment by bjendres** [comment]
That's correct. Only the fields in the "Profile" section are stored per profile

**Comment by jensschuppe** [comment]
This is being taken care of in #92.

**Comment by bjendres** [comment]
Released with ``2.0``
