### ISSUE TITLE
Add a field to know if the receipt was sent by email

### ISSUE THREAD

**Issue by rubofvil** [systopia/de.systopia.donrec#89]
We need to know if the receipt was sent by email or download in a zip(there isn't a possibility to send by email to this contact, don't have a email, ....).
Have sense make a field to set this info when you generate the receipt?

@muniodiego , made this dev, is ok if we manage with a pull request, or is required some adjust?
https://github.com/ixiam/de.systopia.donrec/commit/74dc2ba4fec44254badbe83099d5e40d4c8d62c8

![Image Pasted at 2019-11-6 09-52](https://user-images.githubusercontent.com/2327763/68307057-e2ef5f00-00aa-11ea-9cf7-b82d2e6a5a31.png)

Thanks!

**Comment by bjendres** [comment]
Sounds like a good idea. Go ahead and create a PR and we'll see where to place it, because we have some major restructuring with the profiles coming up...

**Comment by VangelisP** [comment]
Good day @bjendres ! Any updates on this PR and/or the restructuring?

Cheers!

**Comment by bjendres** [comment]
We're in the last steps of creating a 2.0 alpha version, and we'll try to merge this as well. Can't be more than a week or two. Would you be able to help testing then...?

**Comment by VangelisP** [comment]
Of course we will !

**Comment by rubofvil** [comment]
I close the issue, thx for the merge.

**Comment by bjendres** [comment]
Released with ``2.0``
