### ISSUE TITLE
[meta] Refactor profile management

### ISSUE THREAD

**Issue by jensschuppe** [systopia/de.systopia.donrec#92]
This is a meta issue for referencing work being done during the refactoring of profile management.

- Profiles should be stored within a separate database table instead of a CiviCRM settings blob
- More options should be configurable per profile (#85)
- The profile configuration UI should be reworked to be more intuitive
- Profiles should be made deleteable
- [#77] The default profile should be allowed to be deleted - aka any profile should be made markable as default
- Profiles should be locked when they've been already used for issueing receipts
- Profiles should be made markable as active/inactive
- Templates should be stored within the profile itself (HTML content and pdf page size)
- Additional template variables should be configurable
- [#81] "Store Original PDF" setting not handled correctly
- Re-regroup settings in profile form: General settings and "advanced" settings

**Comment by bjendres** [comment]
Released with ``2.0``
