### ISSUE TITLE
Iterate over allowed properties when saving profiles to allow for new properties be added without altering profiles

### ISSUE THREAD

**Issue by pbatroff** [systopia/de.systopia.donrec#97]
When entering default values in setting form

https://github.com/systopia/de.systopia.donrec/blob/037ab08570dbb76386fbb14167f4903fb4fd7114/CRM/Admin/Form/DonrecProfile.php#L459

it iterates over already existing values.

It should however, iterate over a list of registered parameters.

**Comment by jensschuppe** [comment]
The same applies for setting data in the form postprocess:

https://github.com/systopia/de.systopia.donrec/blob/037ab08570dbb76386fbb14167f4903fb4fd7114/CRM/Admin/Form/DonrecProfile.php#L607

Having an array of allowed parameters instead would make it easer to introduce new params in the future without having to update all existing profiles.

**Comment by jensschuppe** [comment]
Available properties are being defined within `CRM_Donrec_Logic_Profile::defaultProfileData()`. Iterating over those instead of the current profile's stored data should do it when saving a profile.

**Comment by bjendres** [comment]
Released with ``2.0``
