### ISSUE TITLE
CiviCRM Donation Receipts Settings

### ISSUE THREAD

**Issue by larnoult** [systopia/de.systopia.donrec#98]
After installation, you need to set a pdf template. The Donation Receipts Settings can be found in the administration console, under the section "CiviContribute". (wp-admin/admin.php?page=CiviCRM&q=civicrm%2Fadmin&reset=1)

**Comment by jensschuppe** [comment]
That's correct, a PDF format is necessary for issueing donation receipts. The PDF format select field is mandatory in the Donation Rreceipts profile (Version 2.0), resp. the message template being used until Version 1.8.

Do you want that to be noted in the documentation or have a validation/status message when there is no PDF format?

**Comment by larnoult** [comment]
Maybe, add a link to the Donation Receipts settings when a user tries to generate a pdf receipt and can not (so far, there was just a red notice not clearly stating where to set the template)
